name: app
description: A Flutter project for demonstrating ZIP file extraction.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For handling ZIP files
  archive: ^3.4.10
  # For getting file system paths
  path_provider: ^2.1.2
  # For manipulating file paths
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true